### ISSUE TITLE
"dvara" set up for my mongoDB help needed i am begging for help

### ISSUE THREAD

**Issue by agwl-saurabh** [magicshui/yico#1]
Sorry for posting here i am in deep trouble. and i don't have your email ID

I want your help in "dvara" set up for my mongoDB instance.  as per the git and google i can't find tutorial for dvara as this is not popular. can you please provide some steps to set up dvara on AWS (i am not able to run). i am new to go and my app is falling and not wokring at all. i am begging you for help as i am paying for server more then i am earning. 

 I am running Parse server open source for my app. and i have lot of request in mongo DB as my app is like instaragaram to lot of images video and Mongo DB request is making my app slow even my app is not wokring as its taking so much merory. I tried mongodb sharding but its not wokring for me and my app is not responding for almost all query.

Right now I am runing my mongo DB on R4.2xlarge server with replica set (as sharding not helpfull for me app). total cost of AWS i am paying more then 1200$ which i can't effort. 

Please please help i only have hope from you to help it will not take 10-15 min for you. please help !!!!!!!
Please provide your email ID 
My email ID is :- agwl.saurabh@outlook.com

**Comment by magicshui** [comment]
hi @agwl-saurabh , we are not using dvara nor aws, so i can only provide you limited help,sorry for that.

Based on my understanding, you can:
1. Build a dvara linux binary 
2. Start a linux server and using supervisord or other tools to start dvara on that server, you can check the cmd options below, it's quite straightforward.
3. Change your's mongodb connection address to your dvara's linux server address

below is dvara's cmd options:
```
Usage of dvara:
  -addrs string
    	comma separated list of mongo addresses (default "localhost:27017")
  -client_idle_timeout duration
    	idle timeout for client connections (default 1h0m0s)
  -dvara.proxy-all
    	if true all queries will be proxied and logger
  -get_last_error_timeout duration
    	timeout for getLastError pinning (default 1m0s)
  -hard_restart
    	if true will drop clients on restart (default true)
  -max_connections uint
    	maximum number of connections per mongo (default 100)
  -max_per_client_connections uint
    	maximum number of connections per client (default 100)
  -message_timeout duration
    	timeout for one message to be proxied (default 2m0s)
  -port_end int
    	end of port range (default 6010)
  -port_start int
    	start of port range (default 6000)
  -server_close_pool_size uint
    	number of goroutines that will handle closing server connections (default 100)
  -server_idle_timeout duration
    	idle timeout for  server connections (default 1h0m0s)
```
